server:
  port: 80

  servlet:
    session:
      timeout: 100m

spring:
  datasource:
    driver-class-name:
    url:
    username:
    password:

  # servlet:
  #   multipart:
  #     max-file-size: 100MB
  #     max-request-size: 200MB

mybatis:
  mapper-locations: mappers/*Mapper.xml
  type-aliases-package: kr.co.moviespring.web.entity
  configuration:
    map-underscore-to-camel-case: true #왜 됨?

logging:
  level:
    kr.co.moviespring.web.repository: trace
