name: auto-build
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd webapps/SpringOfMovie/
            git pull
            ./mvnw package -Dspring.profiles.active=prod
            cd ../
            rm -r ROOT/*
            cd SpringOfMovie/
            unzip target/web-0.0.1-SNAPSHOT.war -d ~/webapps/ROOT/
